layout: stacked
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  # sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 6
  exclude:
    # archived: true
    forks: true
    projects: MonoGamess
    # - repo-name
    

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
    linkedin: renfei-wang-552488173
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

topics:
  - name: Java
    web_url: https://github.com/topics/java
    image_url: https://specials-images.forbesimg.com/imageserve/5e7cce1921695a000666cc29/960x0.jpg?fit=scale

  - name: Full Stack Development
    web_url: https://github.com/topics/full-stack
    image_url: https://pbs.twimg.com/profile_images/1085333629075509249/PVldYUcz.jpg

  - name: Big Data
    web_url: https://github.com/topics/big-data
    image_url: https://codeit.us/storage/S9DtHZsnXGHpsyPrsFQyq3bvg90fAGlN15UUlxv6.png
